#!/usr/bin/env sh

install_path="$HOME/Library/Developer/Xcode/Templates/Swiftest"

echo "Installing templates to $install_path"

rm -rf $install_path
mkdir -p $install_path
cp -R etc/templates/ $install_path

echo "Done!"
